/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfacez;

import java.awt.Color;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
/**
 *
 * @author Erick Piche
 */

//////////Codigo de Hora  ////////////////
public class Inicio extends javax.swing.JFrame implements Runnable{
String hora,minutos,segundos;
Thread hilo;
//////////Codigo de Hora  ////////////////


    /**
     * Creates new form NewJFrame
     */
    
    int x, y;
    public Inicio() {
        initComponents();
        ////////////// Interfacez grafica /////////////////////
        BarraInfo.setVisible(false); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
        Btn_Ocultar_BarrInfo.setVisible(false); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
        Panel_Comiunidad.setVisible(false); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
        Panel_Usuario.setVisible(false); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
        PanelNotificacion_Inferior.setVisible(false); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
        this.setLocationRelativeTo(null);   //Centrar la ventana
        /////////////// Interfacez graficas ///////////////////
        
        ////////// Codigo de Hora  ////////////////
        lbFecha.setText(fecha());
        hilo=new Thread(this);
        hilo.start();
        setVisible(true);
    }
    
    public void hora(){
        Calendar calendario = new GregorianCalendar();
        Date horaactual =new Date();
        calendario.setTime(horaactual);
        hora=calendario.get(Calendar.HOUR_OF_DAY)>9?""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(calendario.HOUR_OF_DAY);
        minutos=calendario.get(Calendar.MINUTE)>9?""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
        segundos=calendario.get(Calendar.SECOND)>9?""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);
    }
    
    public void run (){
        //WHILE
        Thread current =Thread.currentThread();
        
        while (current==hilo) {            
            hora();
            lbHora.setText(hora+":"+minutos);

        }
        //////////Fin Codigo de Hora  ////////////////
    }
    
    //////////////////////////////////Interfaz Grafico////////////////////////////////////////
    ///////////////////////Tag: *hace referencia a interfaces y diseños visual de la aplicacion*    
    /////// comentario: este tag esta añadido a las ordenes que estan relacionadas con el contenido grafico de la aplicacion
    /////// y no obstaculiza ninguna logica ni metodo de este programa  
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Panel_De_Abajo = new javax.swing.JPanel();
        Lb_Fecha = new javax.swing.JLabel();
        lbFecha = new javax.swing.JLabel();
        lbHora = new javax.swing.JLabel();
        Lb_Hora = new javax.swing.JLabel();
        Btn_Amigos = new javax.swing.JButton();
        Btn_Noticias = new javax.swing.JButton();
        PanelPrincipal = new javax.swing.JPanel();
        BarraInfo = new javax.swing.JPanel();
        Panel_Barra_info = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Panel_Barra_De_Arriba = new javax.swing.JPanel();
        Lb_Cerrar_App = new javax.swing.JLabel();
        Iniciar_Sesion = new javax.swing.JLabel();
        Btn_Registrarte = new javax.swing.JButton();
        Panel_Notificacion_Superior = new javax.swing.JPanel();
        cLabel1 = new com.bolivia.label.CLabel();
        Correo = new javax.swing.JButton();
        PanelNotificacion_Inferior = new javax.swing.JPanel();
        Lb_Solicitudes = new javax.swing.JLabel();
        Lb_Mensajes = new javax.swing.JLabel();
        Lb_Articulos = new javax.swing.JLabel();
        Btn_2 = new javax.swing.JButton();
        Btn_1 = new javax.swing.JButton();
        Btn_3 = new javax.swing.JButton();
        N_Solicitudes = new javax.swing.JLabel();
        N_Mensajes = new javax.swing.JLabel();
        N_Articulos = new javax.swing.JLabel();
        Notificaciones = new javax.swing.JButton();
        Panel_De_Arriba_Centrado = new javax.swing.JPanel();
        Btn_Comunidad = new javax.swing.JButton();
        Btn_Usuario = new javax.swing.JButton();
        Btn_Inversionista = new javax.swing.JButton();
        Panel_Comiunidad = new javax.swing.JPanel();
        Lb_Foro = new javax.swing.JLabel();
        Lb_Debutante = new javax.swing.JLabel();
        Lb_Diseño = new javax.swing.JLabel();
        Lb_Categoria = new javax.swing.JLabel();
        Panel_Usuario = new javax.swing.JPanel();
        Lb_Emprededor = new javax.swing.JLabel();
        Lb_Empresario = new javax.swing.JLabel();
        Lb_Proyecto = new javax.swing.JLabel();
        Panel_Home = new javax.swing.JPanel();
        Btn_Home = new javax.swing.JButton();
        Btn_Ocultar_BarrInfo = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_De_Abajo.setBackground(new java.awt.Color(0, 102, 102));

        Lb_Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Lb_Fecha.setText("Fecha");

        lbFecha.setForeground(new java.awt.Color(255, 255, 255));
        lbFecha.setText("DD/MM/YYYY");

        lbHora.setForeground(new java.awt.Color(255, 255, 255));
        lbHora.setText("00:00:00");

        Lb_Hora.setForeground(new java.awt.Color(255, 255, 255));
        Lb_Hora.setText("Hora");

        Btn_Amigos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnamigos.png"))); // NOI18N
        Btn_Amigos.setBorder(null);
        Btn_Amigos.setBorderPainted(false);
        Btn_Amigos.setContentAreaFilled(false);
        Btn_Amigos.setDisabledIcon(null);
        Btn_Amigos.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnamigos2.png"))); // NOI18N
        Btn_Amigos.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnamigos2.png"))); // NOI18N
        Btn_Amigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AmigosActionPerformed(evt);
            }
        });

        Btn_Noticias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnnoticias.png"))); // NOI18N
        Btn_Noticias.setBorder(null);
        Btn_Noticias.setBorderPainted(false);
        Btn_Noticias.setContentAreaFilled(false);
        Btn_Noticias.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnnoticias2.png"))); // NOI18N
        Btn_Noticias.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnnoticias2.png"))); // NOI18N
        Btn_Noticias.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnnoticias2.png"))); // NOI18N
        Btn_Noticias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_NoticiasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_De_AbajoLayout = new javax.swing.GroupLayout(Panel_De_Abajo);
        Panel_De_Abajo.setLayout(Panel_De_AbajoLayout);
        Panel_De_AbajoLayout.setHorizontalGroup(
            Panel_De_AbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_De_AbajoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Btn_Noticias, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 602, Short.MAX_VALUE)
                .addComponent(Btn_Amigos)
                .addGap(8, 8, 8)
                .addGroup(Panel_De_AbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_De_AbajoLayout.createSequentialGroup()
                        .addComponent(Lb_Hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbHora, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_De_AbajoLayout.createSequentialGroup()
                        .addComponent(Lb_Fecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbFecha)))
                .addContainerGap())
        );
        Panel_De_AbajoLayout.setVerticalGroup(
            Panel_De_AbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_De_AbajoLayout.createSequentialGroup()
                .addGroup(Panel_De_AbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_De_AbajoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(Panel_De_AbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Hora)
                            .addComponent(lbHora))
                        .addGap(10, 10, 10)
                        .addGroup(Panel_De_AbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Lb_Fecha)
                            .addComponent(lbFecha)))
                    .addGroup(Panel_De_AbajoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Panel_De_AbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Noticias, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Amigos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(Panel_De_Abajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 940, 80));

        PanelPrincipal.setBackground(new java.awt.Color(0, 153, 153));

        BarraInfo.setBackground(new java.awt.Color(0, 153, 153));

        Panel_Barra_info.setBackground(new java.awt.Color(255, 255, 51));
        Panel_Barra_info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btncerrarsesion1.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btncerrarsesion2.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btncerrarsesion2.png"))); // NOI18N
        Panel_Barra_info.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 70));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/botonHome1.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/botonHome2.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/botonHome2.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Panel_Barra_info.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 60, 70));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btncfg1.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btncfg2.png"))); // NOI18N
        jButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btncfg2.png"))); // NOI18N
        Panel_Barra_info.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 60, 70));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnperfil1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnperfil2.png"))); // NOI18N
        jButton4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnperfil2.png"))); // NOI18N
        Panel_Barra_info.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 60, 70));

        javax.swing.GroupLayout BarraInfoLayout = new javax.swing.GroupLayout(BarraInfo);
        BarraInfo.setLayout(BarraInfoLayout);
        BarraInfoLayout.setHorizontalGroup(
            BarraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Barra_info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BarraInfoLayout.setVerticalGroup(
            BarraInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Barra_info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addComponent(BarraInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 340, Short.MAX_VALUE))
        );

        getContentPane().add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 940, 410));

        Panel_Barra_De_Arriba.setBackground(new java.awt.Color(82, 90, 128));
        Panel_Barra_De_Arriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                Panel_Barra_De_ArribaMouseDragged(evt);
            }
        });
        Panel_Barra_De_Arriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_Barra_De_ArribaMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Panel_Barra_De_ArribaMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Panel_Barra_De_ArribaMouseReleased(evt);
            }
        });
        Panel_Barra_De_Arriba.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lb_Cerrar_App.setBackground(new java.awt.Color(109, 109, 109));
        Lb_Cerrar_App.setFont(new java.awt.Font("Broadway", 1, 36)); // NOI18N
        Lb_Cerrar_App.setForeground(new java.awt.Color(255, 0, 51));
        Lb_Cerrar_App.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Cerrar_App.setText("x");
        Lb_Cerrar_App.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Lb_Cerrar_App.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Lb_Cerrar_AppMouseClicked(evt);
            }
        });
        Panel_Barra_De_Arriba.add(Lb_Cerrar_App, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 50, 40));

        Iniciar_Sesion.setBackground(new java.awt.Color(204, 204, 204));
        Iniciar_Sesion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Iniciar_Sesion.setForeground(new java.awt.Color(255, 255, 255));
        Iniciar_Sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iniciar_Sesion.setText("Iniciar sesión");
        Iniciar_Sesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_Barra_De_Arriba.add(Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 80, 30));

        Btn_Registrarte.setBackground(new java.awt.Color(153, 153, 153));
        Btn_Registrarte.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Registrarte.setText("Registrarse");
        Btn_Registrarte.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Btn_Registrarte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Registrarte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Btn_RegistrarteMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                Btn_RegistrarteMouseReleased(evt);
            }
        });
        Btn_Registrarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RegistrarteActionPerformed(evt);
            }
        });
        Panel_Barra_De_Arriba.add(Btn_Registrarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 120, 30));

        Panel_Notificacion_Superior.setBackground(new java.awt.Color(82, 90, 128));
        Panel_Notificacion_Superior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_Notificacion_SuperiorMouseEntered(evt);
            }
        });

        cLabel1.setBackground(new java.awt.Color(102, 102, 102));
        cLabel1.setText("");

        Correo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/mensaje1.png"))); // NOI18N
        Correo.setBorder(null);
        Correo.setBorderPainted(false);
        Correo.setContentAreaFilled(false);
        Correo.setDisabledIcon(null);
        Correo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/mensaje2.png"))); // NOI18N
        Correo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/mensaje2.png"))); // NOI18N
        Correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CorreoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CorreoMouseExited(evt);
            }
        });
        Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoActionPerformed(evt);
            }
        });

        PanelNotificacion_Inferior.setBackground(new java.awt.Color(82, 90, 110));
        PanelNotificacion_Inferior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelNotificacion_InferiorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelNotificacion_InferiorMouseExited(evt);
            }
        });
        PanelNotificacion_Inferior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lb_Solicitudes.setBackground(new java.awt.Color(204, 204, 204));
        Lb_Solicitudes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lb_Solicitudes.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Solicitudes.setText("Solicitudes");
        Lb_Solicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_SolicitudesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_SolicitudesMouseExited(evt);
            }
        });
        PanelNotificacion_Inferior.add(Lb_Solicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 4, 100, 15));

        Lb_Mensajes.setBackground(new java.awt.Color(204, 204, 204));
        Lb_Mensajes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lb_Mensajes.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Mensajes.setText("Mensajes");
        Lb_Mensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_MensajesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_MensajesMouseExited(evt);
            }
        });
        PanelNotificacion_Inferior.add(Lb_Mensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 27, 100, 15));

        Lb_Articulos.setBackground(new java.awt.Color(204, 204, 204));
        Lb_Articulos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lb_Articulos.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Articulos.setText("Articulos");
        Lb_Articulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_ArticulosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_ArticulosMouseExited(evt);
            }
        });
        PanelNotificacion_Inferior.add(Lb_Articulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 55, 90, 15));

        Btn_2.setBorder(null);
        Btn_2.setBorderPainted(false);
        Btn_2.setContentAreaFilled(false);
        Btn_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_2MouseExited(evt);
            }
        });
        Btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_2ActionPerformed(evt);
            }
        });
        PanelNotificacion_Inferior.add(Btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 30));

        Btn_1.setBorder(null);
        Btn_1.setBorderPainted(false);
        Btn_1.setContentAreaFilled(false);
        Btn_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_1MouseExited(evt);
            }
        });
        Btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_1ActionPerformed(evt);
            }
        });
        PanelNotificacion_Inferior.add(Btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 160, 20));

        Btn_3.setBorder(null);
        Btn_3.setBorderPainted(false);
        Btn_3.setContentAreaFilled(false);
        Btn_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_3MouseExited(evt);
            }
        });
        Btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_3ActionPerformed(evt);
            }
        });
        PanelNotificacion_Inferior.add(Btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 50, 160, 20));

        N_Solicitudes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        N_Solicitudes.setForeground(new java.awt.Color(0, 161, 255));
        N_Solicitudes.setText("&");
        N_Solicitudes.setMaximumSize(new java.awt.Dimension(9, 14));
        PanelNotificacion_Inferior.add(N_Solicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 4, 50, 15));

        N_Mensajes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        N_Mensajes.setForeground(new java.awt.Color(0, 161, 255));
        N_Mensajes.setText("&");
        PanelNotificacion_Inferior.add(N_Mensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 24, 50, 21));

        N_Articulos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        N_Articulos.setForeground(new java.awt.Color(0, 161, 255));
        N_Articulos.setText("&");
        N_Articulos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                N_ArticulosMouseEntered(evt);
            }
        });
        PanelNotificacion_Inferior.add(N_Articulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 53, 50, 19));

        Notificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/notificacion1.png"))); // NOI18N
        Notificaciones.setBorder(null);
        Notificaciones.setBorderPainted(false);
        Notificaciones.setContentAreaFilled(false);
        Notificaciones.setDisabledIcon(null);
        Notificaciones.setDisabledSelectedIcon(null);
        Notificaciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/notificacion2.png"))); // NOI18N
        Notificaciones.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/notificacion2.png"))); // NOI18N
        Notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotificacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_Notificacion_SuperiorLayout = new javax.swing.GroupLayout(Panel_Notificacion_Superior);
        Panel_Notificacion_Superior.setLayout(Panel_Notificacion_SuperiorLayout);
        Panel_Notificacion_SuperiorLayout.setHorizontalGroup(
            Panel_Notificacion_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Notificacion_SuperiorLayout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(PanelNotificacion_Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Panel_Notificacion_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Notificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(Correo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        Panel_Notificacion_SuperiorLayout.setVerticalGroup(
            Panel_Notificacion_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_Notificacion_SuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_Notificacion_SuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_Notificacion_SuperiorLayout.createSequentialGroup()
                        .addComponent(Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Notificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Notificacion_SuperiorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PanelNotificacion_Inferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(Panel_Notificacion_SuperiorLayout.createSequentialGroup()
                        .addComponent(cLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        Panel_Barra_De_Arriba.add(Panel_Notificacion_Superior, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 280, 80));

        Panel_De_Arriba_Centrado.setBackground(new java.awt.Color(82, 90, 128));
        Panel_De_Arriba_Centrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_De_Arriba_CentradoMouseEntered(evt);
            }
        });

        Btn_Comunidad.setForeground(new java.awt.Color(204, 204, 204));
        Btn_Comunidad.setText("Comunidad");
        Btn_Comunidad.setBorder(null);
        Btn_Comunidad.setBorderPainted(false);
        Btn_Comunidad.setContentAreaFilled(false);
        Btn_Comunidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_ComunidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_ComunidadMouseExited(evt);
            }
        });
        Btn_Comunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ComunidadActionPerformed(evt);
            }
        });

        Btn_Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Btn_Usuario.setText("Usuarios");
        Btn_Usuario.setBorder(null);
        Btn_Usuario.setBorderPainted(false);
        Btn_Usuario.setContentAreaFilled(false);
        Btn_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_UsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_UsuarioMouseExited(evt);
            }
        });

        Btn_Inversionista.setForeground(new java.awt.Color(204, 204, 204));
        Btn_Inversionista.setText("Inversionistas");
        Btn_Inversionista.setBorder(null);
        Btn_Inversionista.setBorderPainted(false);
        Btn_Inversionista.setContentAreaFilled(false);
        Btn_Inversionista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_InversionistaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Btn_InversionistaMouseExited(evt);
            }
        });

        Panel_Comiunidad.setBackground(new java.awt.Color(82, 90, 110));
        Panel_Comiunidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_ComiunidadMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_ComiunidadMouseExited(evt);
            }
        });

        Lb_Foro.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Foro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lb_Foro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select1.png"))); // NOI18N
        Lb_Foro.setText("Foro");
        Lb_Foro.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select2.png"))); // NOI18N
        Lb_Foro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Lb_Foro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_ForoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_ForoMouseExited(evt);
            }
        });

        Lb_Debutante.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Debutante.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lb_Debutante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select1.png"))); // NOI18N
        Lb_Debutante.setText("Debutantes");
        Lb_Debutante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Lb_Debutante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_DebutanteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_DebutanteMouseExited(evt);
            }
        });

        Lb_Diseño.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Diseño.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lb_Diseño.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select1.png"))); // NOI18N
        Lb_Diseño.setText("Diseño");
        Lb_Diseño.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Lb_Diseño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_DiseñoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_DiseñoMouseExited(evt);
            }
        });

        Lb_Categoria.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Categoria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Lb_Categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select1.png"))); // NOI18N
        Lb_Categoria.setText("Categoria");
        Lb_Categoria.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Lb_Categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_CategoriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_CategoriaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_ComiunidadLayout = new javax.swing.GroupLayout(Panel_Comiunidad);
        Panel_Comiunidad.setLayout(Panel_ComiunidadLayout);
        Panel_ComiunidadLayout.setHorizontalGroup(
            Panel_ComiunidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ComiunidadLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ComiunidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lb_Diseño, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Lb_Debutante, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(Lb_Foro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Panel_ComiunidadLayout.setVerticalGroup(
            Panel_ComiunidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ComiunidadLayout.createSequentialGroup()
                .addGroup(Panel_ComiunidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb_Foro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lb_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(Lb_Debutante, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(Lb_Diseño, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Panel_Usuario.setBackground(new java.awt.Color(82, 90, 110));
        Panel_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_UsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_UsuarioMouseExited(evt);
            }
        });

        Lb_Emprededor.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Emprededor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select1.png"))); // NOI18N
        Lb_Emprededor.setText("Buscar Emprendedor");
        Lb_Emprededor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_EmprededorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_EmprededorMouseExited(evt);
            }
        });

        Lb_Empresario.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Empresario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select1.png"))); // NOI18N
        Lb_Empresario.setText("Buscar empresario");
        Lb_Empresario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_EmpresarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_EmpresarioMouseExited(evt);
            }
        });

        Lb_Proyecto.setForeground(new java.awt.Color(204, 204, 204));
        Lb_Proyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/select1.png"))); // NOI18N
        Lb_Proyecto.setText("Buscar proyectos");
        Lb_Proyecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Lb_ProyectoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Lb_ProyectoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Panel_UsuarioLayout = new javax.swing.GroupLayout(Panel_Usuario);
        Panel_Usuario.setLayout(Panel_UsuarioLayout);
        Panel_UsuarioLayout.setHorizontalGroup(
            Panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lb_Emprededor, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
            .addComponent(Lb_Proyecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Lb_Empresario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Panel_UsuarioLayout.setVerticalGroup(
            Panel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_UsuarioLayout.createSequentialGroup()
                .addComponent(Lb_Emprededor, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Lb_Empresario, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lb_Proyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_De_Arriba_CentradoLayout = new javax.swing.GroupLayout(Panel_De_Arriba_Centrado);
        Panel_De_Arriba_Centrado.setLayout(Panel_De_Arriba_CentradoLayout);
        Panel_De_Arriba_CentradoLayout.setHorizontalGroup(
            Panel_De_Arriba_CentradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_De_Arriba_CentradoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_Comunidad, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Btn_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Btn_Inversionista)
                .addGap(32, 32, 32))
            .addGroup(Panel_De_Arriba_CentradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Panel_De_Arriba_CentradoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Panel_Comiunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
            .addGroup(Panel_De_Arriba_CentradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_De_Arriba_CentradoLayout.createSequentialGroup()
                    .addContainerGap(77, Short.MAX_VALUE)
                    .addComponent(Panel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        Panel_De_Arriba_CentradoLayout.setVerticalGroup(
            Panel_De_Arriba_CentradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_De_Arriba_CentradoLayout.createSequentialGroup()
                .addGroup(Panel_De_Arriba_CentradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Btn_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_Comunidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Inversionista, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
            .addGroup(Panel_De_Arriba_CentradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_De_Arriba_CentradoLayout.createSequentialGroup()
                    .addContainerGap(19, Short.MAX_VALUE)
                    .addComponent(Panel_Comiunidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(Panel_De_Arriba_CentradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_De_Arriba_CentradoLayout.createSequentialGroup()
                    .addContainerGap(20, Short.MAX_VALUE)
                    .addComponent(Panel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        Panel_Barra_De_Arriba.add(Panel_De_Arriba_Centrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 280, 100));

        Panel_Home.setBackground(new java.awt.Color(82, 90, 128));
        Panel_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Home.setBackground(new java.awt.Color(82, 90, 128));
        Btn_Home.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Home.setForeground(new java.awt.Color(0, 102, 102));
        Btn_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnhome1.png"))); // NOI18N
        Btn_Home.setBorder(null);
        Btn_Home.setContentAreaFilled(false);
        Btn_Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Home.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnhome2.png"))); // NOI18N
        Btn_Home.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnhome2.png"))); // NOI18N
        Btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_HomeMouseEntered(evt);
            }
        });
        Btn_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HomeActionPerformed(evt);
            }
        });
        Panel_Home.add(Btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 70));

        Btn_Ocultar_BarrInfo.setBackground(new java.awt.Color(82, 90, 128));
        Btn_Ocultar_BarrInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btn_Ocultar_BarrInfo.setForeground(new java.awt.Color(0, 102, 102));
        Btn_Ocultar_BarrInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnocultarbarra1.png"))); // NOI18N
        Btn_Ocultar_BarrInfo.setBorder(null);
        Btn_Ocultar_BarrInfo.setContentAreaFilled(false);
        Btn_Ocultar_BarrInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btn_Ocultar_BarrInfo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnocultarbarra2.png"))); // NOI18N
        Btn_Ocultar_BarrInfo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Btn_imagenes/btnocultarbarra2.png"))); // NOI18N
        Btn_Ocultar_BarrInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Btn_Ocultar_BarrInfoMouseEntered(evt);
            }
        });
        Btn_Ocultar_BarrInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ocultar_BarrInfoActionPerformed(evt);
            }
        });
        Panel_Home.add(Btn_Ocultar_BarrInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 70, 70));

        Panel_Barra_De_Arriba.add(Panel_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 90));

        getContentPane().add(Panel_Barra_De_Arriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static  String fecha(){
        Date fecha = new Date();
        SimpleDateFormat formatofecha = new SimpleDateFormat("dd/M/yyyy");
        return formatofecha.format(fecha);
    }
    
    private void Panel_Barra_De_ArribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Barra_De_ArribaMousePressed
        x = evt.getX(); //movimiento de ventana
        y = evt.getY(); //movimiento de ventana 
    }//GEN-LAST:event_Panel_Barra_De_ArribaMousePressed

    private void Panel_Barra_De_ArribaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Barra_De_ArribaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Barra_De_ArribaMouseReleased

    private void Panel_Barra_De_ArribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Barra_De_ArribaMouseDragged
this.setLocation(this.getLocation().x + evt.getX() -x,this.getLocation().y + evt.getY() - y);  //movimiento de la ventana
    }//GEN-LAST:event_Panel_Barra_De_ArribaMouseDragged

    private void Lb_Cerrar_AppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_Cerrar_AppMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Lb_Cerrar_AppMouseClicked

    private void Btn_RegistrarteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_RegistrarteMousePressed
        
        Btn_Registrarte.setBackground(new Color(46, 216, 45)); // para darle color al boton ingresar.
        
    }//GEN-LAST:event_Btn_RegistrarteMousePressed

    private void Btn_RegistrarteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_RegistrarteMouseReleased
       
        try {
            TimeUnit.MICROSECONDS.sleep(300);
                    Btn_Registrarte.setBackground(new Color(153,153,153));// para darle color al boton ingresar
        } catch (InterruptedException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_RegistrarteMouseReleased

    private void Btn_RegistrarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RegistrarteActionPerformed
        this.setVisible(false);  
        OpcionClienteOInversinista c = new OpcionClienteOInversinista();
        c.setVisible(true);
    }//GEN-LAST:event_Btn_RegistrarteActionPerformed

    private void Btn_AmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AmigosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AmigosActionPerformed

    private void CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorreoActionPerformed
        //PanelNotificacion_Inferior.setVisible(true);      //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_CorreoActionPerformed

    private void CorreoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreoMouseEntered
 PanelNotificacion_Inferior.setVisible(true);        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_CorreoMouseEntered

    private void CorreoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CorreoMouseExited
 PanelNotificacion_Inferior.setVisible(true);        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_CorreoMouseExited

    private void PanelNotificacion_InferiorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNotificacion_InferiorMouseEntered
 PanelNotificacion_Inferior.setVisible(true);        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_PanelNotificacion_InferiorMouseEntered

    private void NotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotificacionesActionPerformed
 //PanelNotificacion_Inferior.setVisible(true);        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_NotificacionesActionPerformed

    private void PanelNotificacion_InferiorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelNotificacion_InferiorMouseExited
// PanelNotificacion_Inferior.setVisible(false);        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_PanelNotificacion_InferiorMouseExited

    private void Btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_2ActionPerformed

    private void Btn_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_1MouseEntered
    Btn_1.setForeground(new Color(82,90,110));    //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_1MouseEntered

    private void Btn_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_1MouseExited
       Btn_1.setForeground(new Color(82,90,100)); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_1MouseExited

    private void Btn_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_2MouseEntered
Btn_1.setForeground(new Color(82,90,100));        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_2MouseEntered

    private void Btn_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_2MouseExited
Btn_1.setForeground(new Color(82,90,110));        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_2MouseExited

    private void Btn_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_3MouseEntered
Btn_1.setForeground(new Color(82,90,110));        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_3MouseEntered

    private void Btn_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_3MouseExited
Btn_1.setForeground(new Color(82,90,100));        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_3MouseExited

    private void Btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_1ActionPerformed

    private void Btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_3ActionPerformed

    private void Btn_ComunidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ComunidadMouseEntered
      Btn_Comunidad.setForeground(new Color(255,255,255));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
        Panel_Comiunidad.setVisible(true);  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*

    }//GEN-LAST:event_Btn_ComunidadMouseEntered

    private void Btn_ComunidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ComunidadMouseExited
       Btn_Comunidad.setForeground(new Color(204,204,204));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
     Panel_Comiunidad.setVisible(true);   //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*

    }//GEN-LAST:event_Btn_ComunidadMouseExited

    private void Btn_ComunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ComunidadActionPerformed
       BarraInfo.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ComunidadActionPerformed

    private void Btn_UsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_UsuarioMouseEntered
      Panel_Usuario.setVisible(true);
       Panel_Comiunidad.setVisible(false);
        Btn_Usuario.setForeground(new Color(255,255,255));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_UsuarioMouseEntered

    private void Btn_UsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_UsuarioMouseExited
     Btn_Usuario.setForeground(new Color(204,204,204));   //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_UsuarioMouseExited

    private void Btn_InversionistaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_InversionistaMouseEntered
Panel_Usuario.setVisible(false);
        Btn_Inversionista.setForeground(new Color(255,255,255));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_InversionistaMouseEntered

    private void Btn_InversionistaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_InversionistaMouseExited
      Btn_Inversionista.setForeground(new Color(204,204,204));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Btn_InversionistaMouseExited

    private void N_ArticulosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_N_ArticulosMouseEntered
      // TODO add your handling code here:
    }//GEN-LAST:event_N_ArticulosMouseEntered

    private void Lb_SolicitudesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_SolicitudesMouseEntered
     Lb_Solicitudes.setForeground(new Color(255,255,255));     //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_SolicitudesMouseEntered

    private void Lb_SolicitudesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_SolicitudesMouseExited
       Lb_Solicitudes.setForeground(new Color(204,204,204));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_SolicitudesMouseExited

    private void Lb_MensajesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_MensajesMouseEntered
        Lb_Mensajes.setForeground(new Color(255,255,255));//Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_MensajesMouseEntered

    private void Lb_MensajesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_MensajesMouseExited
       Lb_Mensajes.setForeground(new Color(204,204,204)); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_MensajesMouseExited

    private void Lb_ArticulosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_ArticulosMouseEntered
       Lb_Articulos.setForeground(new Color(255,255,255)); // TODO add your handling code here:
    }//GEN-LAST:event_Lb_ArticulosMouseEntered

    private void Lb_ArticulosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_ArticulosMouseExited
Lb_Articulos.setForeground(new Color(204,204,204));       //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_ArticulosMouseExited

    private void Panel_ComiunidadMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ComiunidadMouseEntered
       Panel_Comiunidad.setVisible(true); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Panel_ComiunidadMouseEntered

    private void Panel_ComiunidadMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ComiunidadMouseExited
      Panel_Comiunidad.setVisible(true);  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Panel_ComiunidadMouseExited

    private void Panel_Notificacion_SuperiorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Notificacion_SuperiorMouseEntered
      //PanelNotificacion_Inferior.setVisible(true); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Panel_Notificacion_SuperiorMouseEntered

    private void Panel_Barra_De_ArribaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Barra_De_ArribaMouseEntered
PanelNotificacion_Inferior.setVisible(false);       //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Panel_Barra_De_ArribaMouseEntered

    private void Lb_ForoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_ForoMouseEntered
       Lb_Foro.setForeground(new Color(255,255,255)); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_ForoMouseEntered

    private void Lb_ForoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_ForoMouseExited
     Lb_Foro.setForeground(new Color(204,204,204));    //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_ForoMouseExited

    private void Lb_DebutanteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_DebutanteMouseEntered
      
        Lb_Debutante.setForeground(new Color(255,255,255)); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_DebutanteMouseEntered

    private void Lb_DebutanteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_DebutanteMouseExited
      
       Lb_Debutante.setForeground(new Color(204,204,204));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_DebutanteMouseExited

    private void Panel_De_Arriba_CentradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_De_Arriba_CentradoMouseEntered
 Panel_Comiunidad.setVisible(false);        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
 Panel_Usuario.setVisible(false);
    }//GEN-LAST:event_Panel_De_Arriba_CentradoMouseEntered

    private void Lb_DiseñoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_DiseñoMouseEntered
      Lb_Diseño.setForeground(new Color(255,255,255));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_DiseñoMouseEntered

    private void Lb_DiseñoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_DiseñoMouseExited
    Lb_Diseño.setForeground(new Color(204,204,204));   //Tag: *hace referencia a interfaces y diseños visual de la aplicacion* 
    }//GEN-LAST:event_Lb_DiseñoMouseExited

    private void Lb_CategoriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_CategoriaMouseEntered
     Lb_Categoria.setForeground(new Color(255,255,255));   //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_CategoriaMouseEntered

    private void Lb_CategoriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_CategoriaMouseExited
     Lb_Categoria.setForeground(new Color(204,204,204));    //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_CategoriaMouseExited

    private void Btn_NoticiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_NoticiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_NoticiasActionPerformed

    private void Lb_EmprededorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_EmprededorMouseEntered
       Lb_Emprededor.setForeground(new Color(255,255,255)); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_EmprededorMouseEntered

    private void Lb_EmprededorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_EmprededorMouseExited
      Lb_Emprededor.setForeground(new Color(204,204,204));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_EmprededorMouseExited

    private void Lb_EmpresarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_EmpresarioMouseEntered
       Lb_Empresario.setForeground(new Color(255,255,255)); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_EmpresarioMouseEntered

    private void Lb_EmpresarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_EmpresarioMouseExited
       Lb_Empresario.setForeground(new Color(204,204,204)); //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_EmpresarioMouseExited

    private void Lb_ProyectoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_ProyectoMouseEntered
      Lb_Proyecto.setForeground(new Color(255,255,255));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_ProyectoMouseEntered

    private void Lb_ProyectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Lb_ProyectoMouseExited
       Lb_Proyecto.setForeground(new Color(204,204,204));  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
    }//GEN-LAST:event_Lb_ProyectoMouseExited

    private void Panel_UsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_UsuarioMouseEntered
Panel_Usuario.setVisible(true);        //Tag: *hace referencia a interfaces y diseños visual de la aplicacion* 
    }//GEN-LAST:event_Panel_UsuarioMouseEntered

    private void Panel_UsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_UsuarioMouseExited
//Panel_Usuario.setVisible(true);    //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*     
    }//GEN-LAST:event_Panel_UsuarioMouseExited

    private void Btn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_HomeMouseEntered
//BarraInfo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_HomeMouseEntered

    private void Btn_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HomeActionPerformed
    Btn_Home.setVisible(false);
    BarraInfo.setVisible(true);
    Btn_Ocultar_BarrInfo.setVisible(true);
    }//GEN-LAST:event_Btn_HomeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Btn_Ocultar_BarrInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_Ocultar_BarrInfoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Ocultar_BarrInfoMouseEntered

    private void Btn_Ocultar_BarrInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ocultar_BarrInfoActionPerformed
     BarraInfo.setVisible(false);  //Tag: *hace referencia a interfaces y diseños visual de la aplicacion*
     Btn_Ocultar_BarrInfo.setVisible(false);
     Btn_Home.setVisible(true);
    }//GEN-LAST:event_Btn_Ocultar_BarrInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraInfo;
    private javax.swing.JButton Btn_1;
    private javax.swing.JButton Btn_2;
    private javax.swing.JButton Btn_3;
    private javax.swing.JButton Btn_Amigos;
    private javax.swing.JButton Btn_Comunidad;
    private javax.swing.JButton Btn_Home;
    private javax.swing.JButton Btn_Inversionista;
    private javax.swing.JButton Btn_Noticias;
    private javax.swing.JButton Btn_Ocultar_BarrInfo;
    private javax.swing.JButton Btn_Registrarte;
    private javax.swing.JButton Btn_Usuario;
    private javax.swing.JButton Correo;
    private javax.swing.JLabel Iniciar_Sesion;
    private javax.swing.JLabel Lb_Articulos;
    private javax.swing.JLabel Lb_Categoria;
    private javax.swing.JLabel Lb_Cerrar_App;
    private javax.swing.JLabel Lb_Debutante;
    private javax.swing.JLabel Lb_Diseño;
    private javax.swing.JLabel Lb_Emprededor;
    private javax.swing.JLabel Lb_Empresario;
    private javax.swing.JLabel Lb_Fecha;
    private javax.swing.JLabel Lb_Foro;
    private javax.swing.JLabel Lb_Hora;
    private javax.swing.JLabel Lb_Mensajes;
    private javax.swing.JLabel Lb_Proyecto;
    private javax.swing.JLabel Lb_Solicitudes;
    private javax.swing.JLabel N_Articulos;
    private javax.swing.JLabel N_Mensajes;
    private javax.swing.JLabel N_Solicitudes;
    private javax.swing.JButton Notificaciones;
    private javax.swing.JPanel PanelNotificacion_Inferior;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel Panel_Barra_De_Arriba;
    private javax.swing.JPanel Panel_Barra_info;
    private javax.swing.JPanel Panel_Comiunidad;
    private javax.swing.JPanel Panel_De_Abajo;
    private javax.swing.JPanel Panel_De_Arriba_Centrado;
    private javax.swing.JPanel Panel_Home;
    private javax.swing.JPanel Panel_Notificacion_Superior;
    private javax.swing.JPanel Panel_Usuario;
    private com.bolivia.label.CLabel cLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lbFecha;
    private javax.swing.JLabel lbHora;
    // End of variables declaration//GEN-END:variables

   

}
